
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Brain MRI Detection",
    page_icon="🧠",
    layout="centered"
)

# ============================================================
# TITLE
# ============================================================

st.title("🧠 Brain MRI Detection")
st.write("Upload an MRI image to classify it into one of four categories.")

st.info(
    "Educational/research project only. "
    "This application is not a medical diagnosis."
)

# ============================================================
# LOAD MODEL
# ============================================================

@st.cache_resource
def load_model():
    return tf.keras.models.load_model("brain_tumor_model.keras")

model = load_model()

# ============================================================
# CLASS NAMES
# IMPORTANT: Must match train.py
# ============================================================

CLASS_NAMES = [
    "Glioma",
    "Meningioma",
    "Pituitary",
    "No Tumor"
]

# ============================================================
# FILE UPLOAD
# ============================================================

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg", "jpeg", "png"]
)

# ============================================================
# PREDICTION
# ============================================================

if uploaded_file is not None:

    # Open image
    img = Image.open(uploaded_file).convert("RGB")

    # Display image
    st.image(
        img,
        caption="Uploaded MRI Image",
        width=300
    )

    # Resize to model input size
    img = img.resize((224, 224))

    # Convert image to NumPy array
    img_array = np.array(img)

    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)

    # IMPORTANT:
    # Do NOT divide by 255 here.
    # EfficientNetB0 handles preprocessing internally.
    
    # Predict
    prediction = model.predict(
        img_array,
        verbose=0
    )[0]

    # Get predicted class
    predicted_index = np.argmax(prediction)

    predicted_class = CLASS_NAMES[predicted_index]

    # Get confidence
    confidence = float(prediction[predicted_index]) * 100

    # ========================================================
    # DISPLAY RESULT
    # ========================================================

    st.subheader("Prediction")

    if predicted_class == "No Tumor":
        st.success(
            f"✅ Result: {predicted_class}"
        )
    else:
        st.warning(
            f"⚠️ Result: {predicted_class}"
        )

    st.write(
        f"**Confidence: {confidence:.2f}%**"
    )

    # ========================================================
    # SHOW ALL CLASS PROBABILITIES
    # ========================================================

    st.subheader("Class Probabilities")

    for i, class_name in enumerate(CLASS_NAMES):

        probability = float(prediction[i]) * 100

        st.write(
            f"{class_name}: {probability:.2f}%"
        )

        st.progress(
            min(probability / 100, 1.0)
        )

    st.caption(
        "The prediction is generated by an EfficientNetB0 "
        "image-classification model."
    )

